-- Start a transaction
BEGIN;

-- Drop existing tables in reverse order of dependency to avoid errors if they already exist.
-- The CASCADE option will also remove dependent objects like indexes and foreign key constraints.
DROP TABLE IF EXISTS comic_pages;
DROP TABLE IF EXISTS comics;
DROP TABLE IF EXISTS scripts;
DROP TABLE IF EXISTS characters;
DROP TABLE IF EXISTS users;
DROP FUNCTION IF EXISTS trigger_set_timestamp;

--
-- Create a reusable function to automatically update the `updated_at` column.
-- This function will be called by triggers on tables that have this column.
--
CREATE FUNCTION trigger_set_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;


--
-- Table: users
-- Stores user account information.
--
CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) UNIQUE NOT NULL,
    password_hash VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

--
-- Table: characters
-- Stores user-created characters.
--
CREATE TABLE characters (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    style_prompt TEXT,
    image_url VARCHAR(255),
    optimized_description TEXT,
    image_job_id VARCHAR(64),
    image_status VARCHAR(20) NOT NULL DEFAULT 'idle',
    image_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create a trigger to update the 'updated_at' timestamp whenever a character is modified.
CREATE TRIGGER set_characters_timestamp
BEFORE UPDATE ON characters
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();


--
-- Table: scripts
-- Stores user-created scripts or stories.
--
CREATE TABLE scripts (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create a trigger to update the 'updated_at' timestamp whenever a script is modified.
CREATE TRIGGER set_scripts_timestamp
BEFORE UPDATE ON scripts
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();


--
-- Table: comics
-- Stores metadata and status for each comic generation task.
--
CREATE TABLE comics (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    script_id INT NOT NULL REFERENCES scripts(id) ON DELETE CASCADE,
    title VARCHAR(200) NOT NULL,
    -- Status can be 'pending', 'processing', 'completed', 'failed'
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
    style_description TEXT NOT NULL DEFAULT 'Classic manga black and white linework',
    aspect_ratio VARCHAR(5) NOT NULL DEFAULT '16:9' CHECK (aspect_ratio IN ('16:9', '9:16', '1:1')),
    pdf_url VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


--
-- Table: comic_pages
-- Stores each generated page of a comic.
--
CREATE TABLE comic_pages (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comic_id INT NOT NULL REFERENCES comics(id) ON DELETE CASCADE,
    page_number INT NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    panel_text TEXT,
    -- Ensures that each page number is unique within a single comic.
    UNIQUE (comic_id, page_number)
);


--
-- Add indexes on foreign key columns for faster lookups.
-- PostgreSQL creates indexes for PRIMARY KEY and UNIQUE constraints automatically, but not for foreign keys.
--
CREATE INDEX ON characters (user_id);
CREATE INDEX ON scripts (user_id);
CREATE INDEX ON comics (user_id);
CREATE INDEX ON comics (script_id);
CREATE INDEX ON comic_pages (comic_id);

-- Commit the transaction
COMMIT;
