-- Start a transaction
BEGIN;

-- Drop existing tables in reverse order of dependency to avoid errors if they already exist.
-- The CASCADE option will also remove dependent objects like indexes and foreign key constraints.
DROP TABLE IF EXISTS comic_page_panels;
DROP TABLE IF EXISTS comic_page_layouts;
DROP TABLE IF EXISTS comic_panel_shots;
DROP TABLE IF EXISTS comic_outline_sections;
DROP TABLE IF EXISTS comic_pages;
DROP TABLE IF EXISTS comic_workflow_stages;
DROP TABLE IF EXISTS comic_characters;
DROP TABLE IF EXISTS comics;
DROP TABLE IF EXISTS scripts;
DROP TABLE IF EXISTS characters;
DROP TABLE IF EXISTS users;
DROP FUNCTION IF EXISTS trigger_set_timestamp;

--
-- Create a reusable function to automatically update the `updated_at` column.
-- This function will be called by triggers on tables that have this column.
--
CREATE FUNCTION trigger_set_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;


--
-- Table: users
-- Stores user account information.
--
CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(128) NOT NULL,
    avatar_index SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

--
-- Table: characters
-- Stores user-created characters.
--
CREATE TABLE characters (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL DEFAULT 'unspecified',
    description TEXT NOT NULL,
    sex VARCHAR(20) NOT NULL DEFAULT 'unspecified',
    is_public BOOLEAN NOT NULL DEFAULT FALSE,
    style_prompt TEXT,
    image_url VARCHAR(255),
    optimized_description TEXT,
    image_job_id VARCHAR(64),
    image_status VARCHAR(20) NOT NULL DEFAULT 'idle',
    image_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create a trigger to update the 'updated_at' timestamp whenever a character is modified.
CREATE TRIGGER set_characters_timestamp
BEFORE UPDATE ON characters
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();


--
-- Table: scripts
-- Stores user-created scripts or stories.
--
CREATE TABLE scripts (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create a trigger to update the 'updated_at' timestamp whenever a script is modified.
CREATE TRIGGER set_scripts_timestamp
BEFORE UPDATE ON scripts
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();


--
-- Table: comics
-- Stores metadata and status for each comic generation task.
--
CREATE TABLE comics (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    script_id INT NOT NULL REFERENCES scripts(id) ON DELETE CASCADE,
    title VARCHAR(200) NOT NULL,
    -- Status can be 'pending', 'processing', 'completed', 'failed'
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
    workflow_stage VARCHAR(20) NOT NULL DEFAULT 'outline',
    workflow_status VARCHAR(20) NOT NULL DEFAULT 'pending',
    style_description TEXT NOT NULL DEFAULT 'Classic manga black and white linework',
    aspect_ratio VARCHAR(5) NOT NULL DEFAULT '16:9' CHECK (aspect_ratio IN ('16:9', '9:16', '1:1')),
    pdf_url VARCHAR(255),
    zip_url VARCHAR(255),
    cover_image_url VARCHAR(255),
    is_public BOOLEAN NOT NULL DEFAULT FALSE,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    job_id VARCHAR(36) UNIQUE,
    error_message TEXT,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_comics_is_public ON comics (is_public);


--
-- Table: comic_characters
-- Associates user-defined characters with comics including ordering and roles.
--
CREATE TABLE comic_characters (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comic_id INT NOT NULL REFERENCES comics(id) ON DELETE CASCADE,
    character_id INT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    order_index INT NOT NULL DEFAULT 1,
    role VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (comic_id, character_id)
);


--
-- Table: comic_workflow_stages
-- Tracks the status for each stage within the generation workflow.
--
CREATE TABLE comic_workflow_stages (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comic_id INT NOT NULL REFERENCES comics(id) ON DELETE CASCADE,
    stage VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    job_id VARCHAR(36),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    error_message TEXT,
    UNIQUE (comic_id, stage)
);


--
-- Table: comic_pages
-- Stores each generated page of a comic.
--
CREATE TABLE comic_pages (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comic_id INT NOT NULL REFERENCES comics(id) ON DELETE CASCADE,
    script_id INT NOT NULL REFERENCES scripts(id) ON DELETE CASCADE,
    page_number INT NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    panel_text TEXT,
    -- Ensures that each page number is unique within a single comic.
    UNIQUE (comic_id, page_number)
);


--
-- Table: comic_outline_sections
-- High-level outline beats stored per comic.
--
CREATE TABLE comic_outline_sections (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comic_id INT NOT NULL REFERENCES comics(id) ON DELETE CASCADE,
    order_index INT NOT NULL,
    title VARCHAR(200),
    summary TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (comic_id, order_index)
);


--
-- Table: comic_panel_shots
-- Panel descriptions derived from outline sections.
--
CREATE TABLE comic_panel_shots (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comic_id INT NOT NULL REFERENCES comics(id) ON DELETE CASCADE,
    outline_section_id INT REFERENCES comic_outline_sections(id) ON DELETE SET NULL,
    sequence_index INT NOT NULL,
    page_number INT,
    panel_number INT,
    description TEXT NOT NULL,
    dialogue TEXT,
    camera_notes VARCHAR(200),
    style_notes TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (comic_id, sequence_index)
);


--
-- Table: comic_page_layouts
-- Stores per-page layout selections and assignments.
--
CREATE TABLE comic_page_layouts (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comic_id INT NOT NULL REFERENCES comics(id) ON DELETE CASCADE,
    page_number INT NOT NULL,
    layout_key VARCHAR(50) NOT NULL DEFAULT 'auto-grid',
    notes TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'suggested',
    selected_at TIMESTAMPTZ,
    comic_page_id INT REFERENCES comic_pages(id) ON DELETE SET NULL,
    UNIQUE (comic_id, page_number)
);


--
-- Table: comic_page_panels
-- Maps panel shots into layout positions per page.
--
CREATE TABLE comic_page_panels (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_layout_id INT NOT NULL REFERENCES comic_page_layouts(id) ON DELETE CASCADE,
    panel_shot_id INT NOT NULL REFERENCES comic_panel_shots(id) ON DELETE CASCADE,
    position INT NOT NULL,
    UNIQUE (page_layout_id, position),
    UNIQUE (page_layout_id, panel_shot_id)
);


--
-- Add indexes on foreign key columns for faster lookups.
-- PostgreSQL creates indexes for PRIMARY KEY and UNIQUE constraints automatically, but not for foreign keys.
--
CREATE INDEX ON characters (user_id);
CREATE INDEX ON characters (is_public);
CREATE INDEX ON scripts (user_id);
CREATE INDEX ON comics (user_id);
CREATE INDEX ON comics (script_id);
CREATE INDEX ON comic_pages (comic_id);
CREATE INDEX ON comic_pages (script_id);
CREATE INDEX ON comic_workflow_stages (comic_id);
CREATE INDEX ON comic_workflow_stages (job_id);
CREATE INDEX ON comic_outline_sections (comic_id);
CREATE INDEX ON comic_panel_shots (comic_id);
CREATE INDEX ON comic_panel_shots (outline_section_id);
CREATE INDEX ON comic_page_layouts (comic_id);
CREATE INDEX ON comic_page_panels (page_layout_id);
CREATE INDEX ON comic_page_panels (panel_shot_id);
CREATE INDEX ON comic_characters (comic_id);
CREATE INDEX ON comic_characters (character_id);

-- Commit the transaction
COMMIT;
