-- Production-safe migration for one-click Auto Mode generation runs.
-- Apply with:
--   psql "$DATABASE_URL" -f migrations/2026-05-11-create-comic-auto-runs.sql

BEGIN;

CREATE TABLE IF NOT EXISTS comic_auto_runs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comic_id INT NOT NULL REFERENCES comics(id) ON DELETE CASCADE,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(32) NOT NULL DEFAULT 'queued',
    current_stage VARCHAR(32) NOT NULL DEFAULT 'story',
    story_snapshot TEXT NOT NULL,
    title_snapshot VARCHAR(255) NOT NULL,
    preferences_snapshot_json TEXT NOT NULL DEFAULT '{}',
    character_review_json TEXT,
    selected_character_ids_json TEXT NOT NULL DEFAULT '[]',
    render_run_id INT REFERENCES comic_render_runs(id) ON DELETE SET NULL,
    abort_requested BOOLEAN NOT NULL DEFAULT FALSE,
    job_id VARCHAR(128),
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_comic_auto_runs_comic_id ON comic_auto_runs (comic_id);
CREATE INDEX IF NOT EXISTS idx_comic_auto_runs_user_id ON comic_auto_runs (user_id);
CREATE INDEX IF NOT EXISTS idx_comic_auto_runs_status ON comic_auto_runs (status);
CREATE INDEX IF NOT EXISTS idx_comic_auto_runs_current_stage ON comic_auto_runs (current_stage);
CREATE INDEX IF NOT EXISTS idx_comic_auto_runs_render_run_id ON comic_auto_runs (render_run_id);
CREATE INDEX IF NOT EXISTS idx_comic_auto_runs_job_id ON comic_auto_runs (job_id);
CREATE INDEX IF NOT EXISTS idx_comic_auto_runs_user_comic_active
    ON comic_auto_runs (user_id, comic_id, status);

COMMIT;
