-- Production-safe migration for queued first/all/remaining page render runs.
-- Apply with:
--   psql "$DATABASE_URL" -f migrations/2026-05-10-create-comic-render-runs.sql

BEGIN;

CREATE TABLE IF NOT EXISTS comic_render_runs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comic_id INT NOT NULL REFERENCES comics(id) ON DELETE CASCADE,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    mode VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'queued',
    current_page_number INT,
    requested_pages_json TEXT NOT NULL DEFAULT '[]',
    completed_pages_json TEXT NOT NULL DEFAULT '[]',
    failed_pages_json TEXT NOT NULL DEFAULT '[]',
    abort_requested BOOLEAN NOT NULL DEFAULT FALSE,
    job_id VARCHAR(36),
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_comic_render_runs_comic_id ON comic_render_runs (comic_id);
CREATE INDEX IF NOT EXISTS idx_comic_render_runs_user_id ON comic_render_runs (user_id);
CREATE INDEX IF NOT EXISTS idx_comic_render_runs_status ON comic_render_runs (status);
CREATE INDEX IF NOT EXISTS idx_comic_render_runs_job_id ON comic_render_runs (job_id);

COMMIT;
